"""Runtime collectors that emit canonical inference optimizer evidence."""

from .mlx import (
    MLXCollectionConfig,
    MLXCollectionResult,
    MLXCollectorError,
    MLXLMRuntime,
    collect_mlx,
)
from .openai_api import (
    API_EVIDENCE_SCHEMA_VERSION,
    ARTIFACT_MANIFEST_NAME,
    ARTIFACT_MANIFEST_SCHEMA_VERSION,
    GLM_REASONING_EFFORT_LEVELS,
    THINKING_TYPES,
    APICollectionConfig,
    APICollectionResult,
    APIEvidence,
    OpenAIStreamCollectorError,
    ProviderExtensions,
    StreamingTransport,
    UrllibStreamingTransport,
    artifact_set_is_complete,
    assert_credential_not_embedded,
    build_request_plan,
    collect_openai_stream,
    redact_text_for_dry_run,
)
from .sse import SSEDecodeError, SSEDecoder, SSEEvent

__all__ = [
    "API_EVIDENCE_SCHEMA_VERSION",
    "ARTIFACT_MANIFEST_NAME",
    "ARTIFACT_MANIFEST_SCHEMA_VERSION",
    "APICollectionConfig",
    "APICollectionResult",
    "APIEvidence",
    "GLM_REASONING_EFFORT_LEVELS",
    "MLXCollectionConfig",
    "MLXCollectionResult",
    "MLXCollectorError",
    "MLXLMRuntime",
    "OpenAIStreamCollectorError",
    "ProviderExtensions",
    "SSEDecodeError",
    "SSEDecoder",
    "SSEEvent",
    "StreamingTransport",
    "THINKING_TYPES",
    "UrllibStreamingTransport",
    "artifact_set_is_complete",
    "assert_credential_not_embedded",
    "build_request_plan",
    "collect_mlx",
    "collect_openai_stream",
    "redact_text_for_dry_run",
]
